# Generated by Django 3.2.13 on 2022-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=60)),
                ('roll', models.IntegerField(unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('regi_no', models.IntegerField(unique=True)),
                ('cgpa', models.FloatField(blank=True)),
            ],
        ),
    ]
